global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:19090']

  # Scrape Pushgateway for synthetic metrics
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:19091']

  # Scrape some APIs if they expose metrics
  - job_name: 'operational-api'
    static_configs:
      - targets: ['operational-api:8080']

  - job_name: 'management-plane-api'
    static_configs:
      - targets: ['management-plane-api:8080']

  - job_name: 'tenant-auth-management-api'
    static_configs:
      - targets: ['tenant-auth-management-api:9090']

  - job_name: 'ztac-ip-reputation-engine-service'
    static_configs:
      - targets: ['ztac-ip-reputation-engine-service:8080']